version: '3.5'
services:
  app:
    build: ./
    ports:
      - '8001:8001'
    container_name: app
    restart: unless-stopped
    depends_on:
      - sql-server
      - redis-server
    environment:
      - DB_PASSWORD=12345
      - EMAIL_SENDER_NAME=test
      - EMAIL_SENDER_ADDRESS=vanech12345@gmail.com
      - EMAIL_SENDER_PASSWORD=lvtirwiticdgmemn
  sql-server:
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
  redis-server:
    image: "redis"
    ports:
      - '6379:6379'
    restart: unless-stopped
