version: '3.5'
services:
  sql-server:
    image: postgres
    container_name: db2
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
  redis-server:
    image: "redis"
    container_name: red
    ports:
      - '6379:6379'
    restart: unless-stopped
    
