apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: golangschool
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: servicepdb
spec:
  selector:
    app: postgredb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: servicerdb
spec:
  selector:
    app: redisdb
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer
